mongodb:
  uri: '127.0.0.1:27017'
  database: 'statsnba'

rdbs: 'postgresql://postgres:@localhost:5432/statsnba'

data:
  development: 'data/statsnba'
  test: 'data/tests'

database:
  test: 'statsnba_test'
  development: 'statsnba_dev'
  production: 'statsnba'
